CREATE TABLE [dbo].[FinancialAidType](
	[AidTypeID] [int] IDENTITY(1,1) NOT NULL,
	[AidType] [varchar](25) NOT NULL,
 CONSTRAINT [PK_FinancialAidType] PRIMARY KEY CLUSTERED 
(
	[AidTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]