CREATE TABLE [dbo].[HighSchool](
	[HighSchoolID] [int] IDENTITY(1,1) NOT NULL,
	[HighSchool] [varchar](255) NOT NULL,
 CONSTRAINT [PK_HighSchools] PRIMARY KEY CLUSTERED 
(
	[HighSchoolID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]