CREATE TABLE [dbo].[IncomeLevel](
	[IncomeLevelID] [int] IDENTITY(1,1) NOT NULL,
	[IncomeLevel] [varchar](50) NOT NULL,
 CONSTRAINT [PK_IncomeLevel] PRIMARY KEY CLUSTERED 
(
	[IncomeLevelID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]